# Generated by Django 4.2.25 on 2025-10-26 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('adventure', 'Adventure'), ('thriller', 'Thriller'), ('drama', 'Drama'), ('other', 'Other')], default='other', max_length=100)),
                ('initial_prompt', models.TextField(help_text='The starting prompt or premise for the story')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='story_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('max_contributors', models.IntegerField(default=10)),
                ('current_state', models.TextField(blank=True, help_text='Latest story content')),
                ('is_completed', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('is_branch_point', models.BooleanField(default=False, help_text='Whether this node allows for branching')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stories.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='stories.story')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stories.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stories.story')),
            ],
        ),
        migrations.CreateModel(
            name='AIWritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('plot_twist', 'Plot Twist'), ('character', 'Character Development'), ('dialogue', 'Dialogue'), ('setting', 'Setting Description'), ('conflict', 'Conflict Generation'), ('continuation', 'Story Continuation'), ('description', 'Scene Description')], max_length=50)),
                ('generated_text', models.TextField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField(blank=True, help_text='The story context used to generate this prompt')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storynode')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes_created', models.IntegerField(default=0)),
                ('words_contributed', models.IntegerField(default=0)),
                ('last_contribution', models.DateTimeField(auto_now=True)),
                ('first_contribution', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'story')},
            },
        ),
    ]
