# Generated by Django 4.2.25 on 2025-10-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='archive_reason',
            field=models.CharField(blank=True, help_text='Reason for archiving', max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the story was archived', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived the story', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether the story is archived (hidden from public)'),
        ),
    ]
